/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "alpha_trade_constants.h"



const alpha_tradeConstants g_alpha_trade_constants;

alpha_tradeConstants::alpha_tradeConstants() {
}



