/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef alpha_config_CONSTANTS_H
#define alpha_config_CONSTANTS_H

#include "alpha_config_types.h"



class alpha_configConstants {
 public:
  alpha_configConstants();

};

extern const alpha_configConstants g_alpha_config_constants;



#endif
