/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef alpha_trade_CONSTANTS_H
#define alpha_trade_CONSTANTS_H

#include "alpha_trade_types.h"



class alpha_tradeConstants {
 public:
  alpha_tradeConstants();

};

extern const alpha_tradeConstants g_alpha_trade_constants;



#endif
