/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "alpha_config_constants.h"



const alpha_configConstants g_alpha_config_constants;

alpha_configConstants::alpha_configConstants() {
}



